app1/urls.py
from app1.views import *
from django.urls import path
app_name='something'
urlpatterns=[
    path('sai',sai,name='sai')
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('response',response,name='response')
]

specificurlnavigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sai(request):
    return render(request,'sai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def response(request):
    return render(request,'response.html')

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
    <h1>naku telusu le babu</h1>
    <h1>poi panichuskoni savpoo</h1>
    <a href="{% url 'something:sai' %}"><h1>response of sai </h1></a>

    </center>

</body>
</html>

templates/sai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>hey ammai nuv chala bagunav</h1>
        <h1>kudirithe cup coffe </h1>
        <a href="{% url 'nothing:response' %}"><h1>reply for response</h1></a>
    </center>
</body>
</html>